
Epoch: 1/50
    32/144000: [>...............................] - ETA 0.0s
Traceback (most recent call last):
  File "main_fusion.py", line 137, in <module>
    run(cfg)
  File "main_fusion.py", line 109, in run
    amp         = cfg['TRAINING']['amp'])
  File "/home/inho/df_detection/experiments_OC/train_fusion.py", line 185, in fit
    train_metrics = train(model1, model2, trainloader, criterion1, criterion2, consistency_rate, optimizer, log_interval, device, amp)
  File "/home/inho/df_detection/experiments_OC/train_fusion.py", line 55, in train
    loss_ce = criterion1(outputs, targets) # Cross entropy
  File "/home/inho/anaconda3/envs/df_detection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given